### ISSUE TITLE
[Refactor] 공지방 메인 수정사항 

### ISSUE THREAD

**Issue by lsy1307** [UMC-README/front-end#161]
# 제목

## 작업내용

- [x] 헤더에 room title띄우기
- [x] 헤더 뒤로가기 경로 변경
- [x] 공지글 사진 없을 경우 빈공간 삭제

**Comment by imi21123** [comment]
Fix는 오류 수정 느낌이 강해서 이런 경우에는 Refactor로 하는게 더 좋을 것 같아요!
